# Generated by Django 5.2.8 on 2026-05-26 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_city_customuser_country_customuser_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='isProfileCompleted',
            field=models.BooleanField(default=False),
        ),
    ]
